# We start from Anyscale's ray image. The image from `ray-project` should also work.
FROM anyscale/ray:2.43.0-slim-py312-cu124


RUN sudo apt-get update -y && sudo apt-get install -y wget kmod libxml2 build-essential
RUN wget https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda_12.4.0_550.54.14_linux.run \
    && sudo sh cuda_12.4.0_550.54.14_linux.run --silent --toolkit

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN echo "export RAY_RUNTIME_ENV_HOOK=ray._private.runtime_env.uv_runtime_env_hook.hook" >> /home/ray/.bashrc

RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends --allow-change-held-packages \
    vim \
    iputils-ping \
    iproute2 \ 
    openmpi-bin \
    openmpi-common \
    libopenmpi-dev \
    libnccl2 \
    libnccl-dev \
    openssh-server \
    ca-certificates \ 
    infiniband-diags \
    ibverbs-utils