name: SkyRL

on: 
  push: 
    branches: 
      - main 
      - rc/**
  pull_request:

permissions:
  checks: write   # for status checks to appear
  contents: read

# Cancel runs for previous commits on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          cache: 'pip'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Run pre-commit hooks
        run: uv pip install pre-commit; pre-commit run --all-files --config .pre-commit-config.yaml
  
  skyrl_tests:
    needs: check_code_quality
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./skyrl-train

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          cache: 'pip'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install skyrl-train
        run:  uv sync --frozen --extra dev # installs from lock file
      - name: Run cpu tests
        run:  uv run --frozen pytest tests/cpu/
  
  skyrl_gym_tests:
    needs: check_code_quality
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./skyrl-gym

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          cache: 'pip'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install skyrl-gym
        run:  uv sync --frozen --extra dev # installs from lock file
      - name: Run cpu tests
        run:  uv run --frozen pytest tests/